### ISSUE TITLE
Gallery is not loaded in browser after adding plugin and dependencies 

### ISSUE THREAD

**Issue by haimari** [blueswen/mkdocs-glightbox#15]
Hello, tried to add the plugin and create a gallery, but it does not seem to work.
Even though when inspecting browser I see the JS loads

<img width="2043" alt="image" src="https://user-images.githubusercontent.com/11332517/227759715-ef98cc6b-5431-4711-b4f1-8792fe4efaf4.png">

## `Dockerfile`

```Dockerfile
FROM squidfunk/mkdocs-material

COPY requirements.txt .

RUN apk add --no-cache gcc musl-dev

RUN pip install -r requirements.txt
```

## Python `requirements.txt`

```
mkdocs==1.4.2
mkdocs-awesome-pages-plugin==2.2.1
mkdocs-git-revision-date-localized-plugin==0.5.2
mkdocs-material==5.2.2
mkdocs-material-extensions==1.0
mkdocs-minify-plugin==0.3.0
jinja2==3.0.3
beautifulsoup4>=4.11.1
mkdocs-glightbox

```

## `mkdocs.conf`

```yaml
plugins:
  - search
  - awesome-pages
  - minify:
      minify_html: true
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: false
      draggable: false
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
```

## Extra(`mkdocs.yml`)

```yaml
extra_javascript:
  - javascripts/glightbox.min.js


extra_css:
  - stylesheets/extra.css
  - stylesheets/glightbox.min.css
```

## The image code in mkdocs the page

```
![Taipei, Taiwan. Credit: Yuyu Liu](/img/jump.jpg){data-gallery="taipei"}

![Taipei, Taiwan. Credit: Yuyu Liu](/img/pit.jpg){data-gallery="taipei"}
```

## Website to inspect the issue (the last two images in the page)
https://www.rc-drive.com/
