### ISSUE TITLE
Force captions in lightbox to always be white on black

### ISSUE THREAD

**Issue by patrislav1** [blueswen/mkdocs-glightbox#32]
The caption shown in the lightbox seems to inherit the currently selected color scheme. So when the [light theme (aka default theme)](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette-toggle) is selected, the lightbox shows a bright black-on-white caption box which can look unpleasant and distract from the image (esp. when the image is low key). Since the lightbox itself always has a black background, it would make a lot of sense to force the lightbox caption to always have white(ish) text on black background, regardless of currently selected color theme. Is there a way to do so, without modifying the source code?

**Comment by Lexachoc** [comment]
You can do modify the css (for example, using `extra.css`)

load it in the `mkdocs.yml`
```yml
extra_css:
  - stylesheets/extra.css
```

and then in `extra.css`
```css
.glightbox-clean .gslide-description {
    background: rgba(0,0,0,.92) !important;
}

.gslide-title, .gslide-desc {
    color: #fff !important;
}
```

The result:
![image](https://github.com/blueswen/mkdocs-glightbox/assets/20377719/f50da88f-e6ce-4d17-8a6d-63e6ed58ac1e)

**Comment by Lexachoc** [comment]
ah sorry about that! Use the below one instead!

```css
.gdesc-inner {
    background: rgba(0,0,0,.92) !important;
}

.gslide-title, .gslide-desc {
    color: #fff !important;
}
```
