### ISSUE TITLE
Effects and custom config parameters not working

### ISSUE THREAD

**Issue by charlstown** [blueswen/mkdocs-glightbox#46]
Hello there

Sorry I’m not able to make the configuration parameters work, neither the effect on hover is working. Did I do something wrong? The plugin is working perfectly but nothing changes with or without the config parameters. I tried to change the `effect` in the`plugins/glighbox` section but on hover there is no effect, I tried to modify the `slide_effect` too but same result.

```yaml
# Extensions
markdown_extensions:
  - abbr
  - admonition            # Block elements
  - pymdownx.details      # Collapsible call-outs
  - pymdownx.superfences  # Nested elements
  - pymdownx.mark         # Hihlighting text
  - attr_list             # To add buttons
  - md_in_html            # To add html in markdown (centred images)
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Plugins
plugins:
  - search
  - markdownextradata
  - awesome-pages
  - glightbox:
      touchNavigation: true
      loop: true
      effect: zoom
      slide_effect: fade
      width: 100%
      height: auto
      zoomable: false
      draggable: true
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false

# css
extra_css:
  - assets/stylesheets/extra.css

# javascript
extra_javascript:
  - assets/javascripts/extra.
 
…
```

Thanks for the awesome gallery!
